# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Args',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Gay')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=1)),
                ('createTime', models.DateTimeField(default='2016-10-13 16:53:42')),
                ('memo', models.CharField(max_length=2000)),
                ('userGroup', models.ManyToManyField(to='myapp.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeNme', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserType'),
        ),
    ]
