# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=1)),
                ('createTime', models.DateTimeField(default='2016-10-13 16:53:42')),
                ('memo', models.TextField(default='Remark')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserType'),
        ),
    ]
