# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='typeId',
        ),
        migrations.AddField(
            model_name='usertype',
            name='typeNme',
            field=models.CharField(default='', max_length=20),
        ),
    ]
