# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161013_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='memo',
            field=models.CharField(max_length=2000),
        ),
    ]
