# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20161013_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Args',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
