# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='args',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='args',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Gay')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='args',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
